"""Seer fill simulator: pure, deterministic order lifecycle and portfolio accounting.

One code path for the backtest (P3) and nightly paper trading (P4). No database, no
network, no clock: importing this package must never load psycopg, requests or yfinance
(enforced by tests/test_sim_purity.py).

Per session S: ``apply_split`` (only if a split executes on S) -> ``step(S)`` -> persist
events and snapshot -> ``size_picks(..., next session)``. See engine/package_readme.md.

P7a adds trade rules as a value (``sim.rules``: ``TradeRules``, ``DESIGN_V0`` and the presets)
and the book engine every non-default rule set runs on (``sim.book``: ``step_book``, and
``apply_book_split`` for splits on live book positions).
``DESIGN_V0`` keeps running on ``size_picks`` + ``step`` above, unchanged. A second bracket rule
set is expressible as ``engine="bracket"`` (``DESIGN_V0_GOTRADE``, §5 at Gotrade's measured fee
schedule); ``sim.charges`` prices the bracket path's money from whichever rule set it is handed.
"""

from seer_engine.sim.book import (
    WEIGHT_QUANTUM,
    Book,
    BookSnapshot,
    BookSplit,
    BookStep,
    Fill,
    Position,
    Target,
    Trade,
    apply_book_split,
    close_book_unpriced,
    equal_weight,
    new_book,
    step_book,
    to_weight,
)
from seer_engine.sim.charges import bracket_rules, buy_cash, order_fee, sell_cash, whole_shares_for
from seer_engine.sim.lifecycle import close_unpriced, step
from seer_engine.sim.model import (
    COST_RATE,
    SLOTS,
    TIME_STOP_DAYS,
    Event,
    EventKind,
    ExitReason,
    Order,
    OrderStatus,
    Portfolio,
    Snapshot,
    StepResult,
    buy_cost,
    initial_cash_usd,
    new_portfolio,
    q,
    sell_proceeds,
)
from seer_engine.sim.rules import (
    BRACKET_ENGINES,
    DAILY_SWITCH,
    DAILY_SWITCH_TBILL,
    DEFAULT_ETFS,
    DESIGN_V0,
    DESIGN_V0_GOTRADE,
    LEVERAGED_ETFS,
    MONTHLY_HOLD,
    MONTHLY_HOLD_FRAC,
    MONTHLY_HOLD_TBILL,
    MONTHLY_RANK_WEEKLY_RESIZE,
    MONTHLY_RANK_WEEKLY_RESIZE_FRAC,
    MONTHLY_RANK_WEEKLY_RESIZE_TBILL,
    OPEN_LIMIT_BAND,
    PRESETS,
    RESIZE_BAND,
    SHARE_QUANTUM,
    SWING_T10,
    SWING_T20,
    SWING_T20_OPEN,
    V0_BOOK,
    WEEKLY_HOLD,
    TradeRules,
    describe_rules,
    is_bracket,
    is_decision_session,
    is_rank_session,
    is_resize_session,
    rule_owner_inputs,
)
from seer_engine.sim.sizing import Pick, RejectReason, Rejection, SizingResult, size_picks
from seer_engine.sim.split_adjust import apply_split

__all__ = [
    "BRACKET_ENGINES",
    "COST_RATE",
    "DAILY_SWITCH",
    "DAILY_SWITCH_TBILL",
    "DEFAULT_ETFS",
    "DESIGN_V0",
    "DESIGN_V0_GOTRADE",
    "LEVERAGED_ETFS",
    "MONTHLY_HOLD",
    "MONTHLY_HOLD_FRAC",
    "MONTHLY_HOLD_TBILL",
    "MONTHLY_RANK_WEEKLY_RESIZE",
    "MONTHLY_RANK_WEEKLY_RESIZE_FRAC",
    "MONTHLY_RANK_WEEKLY_RESIZE_TBILL",
    "OPEN_LIMIT_BAND",
    "PRESETS",
    "RESIZE_BAND",
    "SHARE_QUANTUM",
    "SLOTS",
    "SWING_T10",
    "SWING_T20",
    "SWING_T20_OPEN",
    "TIME_STOP_DAYS",
    "V0_BOOK",
    "WEEKLY_HOLD",
    "WEIGHT_QUANTUM",
    "Book",
    "BookSnapshot",
    "BookSplit",
    "BookStep",
    "Event",
    "EventKind",
    "ExitReason",
    "Fill",
    "Order",
    "OrderStatus",
    "Pick",
    "Portfolio",
    "Position",
    "RejectReason",
    "Rejection",
    "SizingResult",
    "Snapshot",
    "StepResult",
    "Target",
    "Trade",
    "TradeRules",
    "apply_book_split",
    "apply_split",
    "bracket_rules",
    "buy_cash",
    "buy_cost",
    "close_book_unpriced",
    "close_unpriced",
    "describe_rules",
    "equal_weight",
    "initial_cash_usd",
    "is_bracket",
    "is_decision_session",
    "is_rank_session",
    "is_resize_session",
    "new_book",
    "new_portfolio",
    "order_fee",
    "q",
    "rule_owner_inputs",
    "sell_cash",
    "sell_proceeds",
    "size_picks",
    "step",
    "step_book",
    "to_weight",
    "whole_shares_for",
]
