/**
 * The method-lab snapshot, bundled at build time. Regenerated by `lab stage` on every lab commit.
 * Import only from server components: the JSON is large and must not ship to the browser.
 */
import raw from '../../data/lab.json';
import { trialsByMethod } from './derive';
import type { LabInsight, LabMethod, LabSnapshot, LabTrial } from './types';

export const lab = raw as unknown as LabSnapshot;

const methodsById = new Map(lab.methods.map((m) => [m.id, m]));
const trialsById = trialsByMethod(lab.trials);

export const methodById = (id: string): LabMethod | undefined => methodsById.get(id);

/** A method's trials, ordered by n. */
export const trialsOf = (methodId: string): LabTrial[] => trialsById.get(methodId) ?? [];

/** Insights tied to a method, ordered by id. */
export const insightsOf = (methodId: string): LabInsight[] =>
  lab.insights.filter((i) => i.methodId === methodId).sort((a, b) => a.id - b.id);

/** Methods whose parent is `methodId`, ordered by id. */
export const childrenOf = (methodId: string): LabMethod[] =>
  lab.methods.filter((m) => m.parentId === methodId).sort((a, b) => a.id.localeCompare(b.id));
